dist: bionic
os: linux
language: shell

language: go

go:
  - 1.12.x

services:
  - docker

env:
  global:
    - DOCKER_PLATFORMS="linux/amd64,linux/arm64,linux/ppc64le,linux/s390x,linux/386,linux/arm/v7,linux/arm/v6"
    - APP_FOLDER=/go/src/github.com/moikot/smartthings-metrics/

git:
  depth: 1

before_install:
  - go get github.com/mattn/goveralls

stages:
  - name: build and test
    if: tag IS blank
  - name: deploy
    if: branch = master OR tag =~ /^v[0-9]+\.[0-9]+\.[0-9]+$/

matrix:
  include:

    - stage: build and test
      script:
        # Run all the tests and report the coverage
        - go test -covermode=count -coverprofile=profile.cov -coverpkg=./... ./...
        - $GOPATH/bin/goveralls -coverprofile=profile.cov -service=travis-ci

    - stage: deploy
      script:
        # Get scripts for building Docker images
        - id=$(docker create moikot/docker-tools)
        - docker cp $id:/scripts.sh /tmp/scripts.sh && docker rm -v $id
        # Update docker to the latest version and enable BuildKit
        - /tmp/scripts.sh update_docker
        # Login to Doker Hub
        - >-
          echo "${DOCKER_PASSWORD}" |
          docker login -u "${DOCKER_USERNAME}" --password-stdin
        # Build multi-platform image and push it
        - >-
          /tmp/scripts.sh build_images
          ${TRAVIS_REPO_SLUG} ${TRAVIS_BRANCH} ${DOCKER_PLATFORMS}
          --push --build-arg APP_FOLDER=${APP_FOLDER}
        # Push readme file for a tag
        - |
          if [ "${TRAVIS_BRANCH}" != "master" ]; then
              /tmp/scripts.sh push_readme \
              ${TRAVIS_REPO_SLUG} README.md \
              ${DOCKER_USERNAME} ${DOCKER_PASSWORD}
          fi

notifications:
  email: false
